export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { EcosystemSection } from './EcosystemSection'
export { ChallengesSection } from './ChallengesSection'
export { MethodologySection } from './MethodologySection'
export { AchievementsSection } from './AchievementsSection'
export { ImpactSection } from './ImpactSection'
export { FutureSection } from './FutureSection'
export { FooterSection } from './FooterSection'

export { AboutSection } from './AboutSection'
export { EcosystemSection } from './EcosystemSection'
export { ChallengesSection } from './ChallengesSection'
export { MethodologySection } from './MethodologySection'
export { AchievementsSection } from './AchievementsSection'
export { ImpactSection } from './ImpactSection'
export { FutureSection } from './FutureSection'
export { FooterSection } from './FooterSection'

